# Generated by Django 2.1.2 on 2018-12-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orden',
            name='idAscensor',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orden',
            name='modelo',
            field=models.PositiveIntegerField(),
        ),
    ]
