# Generated by Django 2.1.2 on 2018-12-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181208_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tecnicoAsignado',
            field=models.ManyToManyField(to='app.Tecnico'),
        ),
    ]
